### ISSUE TITLE
[Bug] Severity order is opposite

### ISSUE THREAD

**Issue by Nanamachi** [d9705996/perl-toolbox#21]
According to [perlcritic Documentation](https://metacpan.org/pod/perlcritic#CONFIGURATION), `gentle` means the highest severity and `brutal` means the lowest. These severity words means "How critics act", not "How codes act".
The setting in `package.json`, however, regards `brutal` is a `warning` severity and `gentle` is a `hint`. It seems opposite.

**Comment by d9705996** [comment]
@Nanamachi - The extension provides configuration to allow you to choose whatever `perlcritic -> VSCode` severity mappings that make sense for you.  e.g.

```json
"perl-toolbox.lint.brutal": "critical",
````

The default settings in `package.json` are simply my preference so not something I would be looking to *fix*.

**Comment by Nanamachi** [comment]
No, I don't mean that. I'm saying that `brutal` config must be equal or lesser severity than any others.

**Comment by Nanamachi** [comment]
I mean, instead, is like this.

[perl critic's severity meaning]
(most severe) gentle > stern > harsh > cruel > brutal (least severe)

[perl-toolbox's severity]
(least severe) gentle(hint) < stern(info) = harsh(info) < cruel(warning) = brutal(warning) (most severe)

**Comment by d9705996** [comment]
@Nanamachi - I have had another look through the documentation you provided and the source code of some of the policies and I now better understand your thinking and i somewhat agree.  However I still not convinced enough to change the defaults for the extension as this would have unexpected consequences for any users who have not customised the default settings as VScode will auto update the extension changing their observed behaviour..

Since there is already settings to enable customisation you require and it is highly unlikely there is a *correct* defaults that everyone will be happy I am going to leave as-is.  

Please let me know if there is something I have missed that means the extension doesn't work for you, even if it means you have to make some config changes.
