### ISSUE TITLE
failing to read libs?

### ISSUE THREAD

**Issue by duartemolha** [d9705996/perl-toolbox#9]
I previous question has really not an issue with your plugin and I appologise for wasting you time...

but I have another issue that might be.

I have a part of my code that finds additional libs to include on my script.

I have a repo organised as follows:

MYREPO/
     /bin/script_to_run.pl
     /lib/UTILS/Repo_version.pl

In order to make use the code is portable I include the lib at runtime on my code like this:

```
	use FindBin qw($Bin);
	use lib "$Bin/../lib";
	use UTILS::Repo_version;
```

The scripts_to_run.pl  works fine on my linux server. And is able to import my lib modules.
But on windows (using strawberry perl) is seems VScode is not reading the additional libs even though they seem included on the @INC (see error)

> Can't locate UTILS/Repo_version.pm in @INC (you may need to install the UTILS::Repo_version module) (@INC contains: w:/src/MYREPO/../lib C:/Strawberry/perl/site/lib C:/Strawberry/perl/vendor/lib C:/Strawberry/perl/lib) at - line 12.

If this something I need to change in order for the error to go away?

**Comment by d9705996** [comment]
@duartemolha - have you tried adding the paths in the VSCode settings to 

`perl-toolbox.syntax.includePaths`

**Comment by duartemolha** [comment]
I did now... but still no joy

I tried adding it to my user settings file and also to my workspace settings

{
"perl-toolbox.syntax.includePaths": ["W:/src/ngs_toolbox/lib"],
}

Also, would that be the only way to make the code load these libraries?

I much rather it would read the inputs folders to include from the script
if I could.

Thanks

Duarte

**Comment by d9705996** [comment]
@duartemolha - to be honest the way I am doing syntax highlgihting is really primative.  The plugin uses `perl -c` as the base command and then adds `-I <directory>` for each includePath.  

This works for my use case so I am unlikely to extend the plugin unless it is really simple.  If you can manage to find a working command that fits you needs then share it and I will see if it can be added. Otherwise I will close the issue.

I would also be open to merging a [PR](https://github.com/d9705996/perl-toolbox/compare) if you want to help add this feature
